fragment continentFragment on Continent {
  code
  name
}

query ContinentsShallow {
  continents {
    ...continentFragment
  }
}


query ContinentsFiltered($continentCode: String!) {
  continents(filter: {code: {eq: $continentCode}}) {
    ...continentFragment
    countries {
      name
    }
  }
}

query ContinentsFilteredDeep($continentCode: String!) {
  continents (filter: {code: {eq: $continentCode}}) {
    ...continentFragment
    countries {
      code
      name
      capital
      languages {
        code
        name
      }
      states {
        code
        name
      }
    }
  }
}

query Languages {
  languages {
    code
    name
    native
  }
}
